name: Demo SonarQube Analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  sonar-scan:
    uses: ./.github/workflows/sonar-scan-cli-oss-prj-reusable.yaml
    secrets: inherit
    with:
      github_repo_slug: spf13/afero
